# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'signinDemo' do
    pod 'Google/SignIn'
    pod 'FBSDKCoreKit','~>4.5.1'
    pod 'FBSDKShareKit','~>4.5.1'
    pod 'FBSDKLoginKit','~>4.5.1'
#    pod 'MMDrawerController', '~> 0.5.7'
    pod 'SWRevealViewController', '~> 2.3'
    pod 'SPXDataValidators', '~> 1.4'
    pod 'JDFTooltips', '~> 1.1'
    pod 'Stripe'
    pod 'PayPal-iOS-SDK'

end

